# the gitpod-provided dockerfile provides the deafult gitpod environment with the addition of Postgres

image:
  file: .gitpod.dockerfile

tasks:
  - name: LL terminal
    init: |
      brew tap heroku/brew
      brew install heroku
      brew install redis
      nvm install 0.12.7
      npm install -g yuglify
      brew install forego
      pyenv install 2.7.16
      pip2.7 install virtualenv
      virtualenv venv --python=python2.7
      createdb layuplist
    command: |
      nvm use 0.12.7


ports:
  - port: 3000
    onOpen: open-preview
    name: website
    description: Website Preview
  - port: 5432
    onOpen: ignore
    name: db
    description: Postgres Database



vscode:
  extensions:
    - ms-python.python