# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='upvotes',
        ),
    ]
