# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20160204_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='category',
            field=models.CharField(choices=[('GOOD', 'Good'), ('LAYUP', 'Layup')], db_index=True, max_length=8),
        ),
    ]
