# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20160208_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('course', 'user', 'category')]),
        ),
    ]
