# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20160208_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
