# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20160212_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 4, 22, 22, 26, 794766, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 4, 22, 22, 32, 906650, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
