# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20160319_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
