# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20161026_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='layup_score',
            new_name='difficulty_score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='layup_sentiment',
            new_name='difficulty_sentiment',
        ),
        migrations.AlterField(
            model_name='vote',
            name='category',
            field=models.CharField(choices=[('quality', 'Quality'), ('difficulty', 'Difficulty')], db_index=True, max_length=16),
        ),
    ]
