# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20161206_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='course_registration_number',
            field=models.IntegerField(),
        ),
    ]
