# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_allow_duplicate_course_registration_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='course_registration_number',
            field=models.IntegerField(null=True),
        ),
    ]
