# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_allow_null_course_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='course_offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.CourseOffering'),
        ),
    ]
