# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GOOD', 'Good'), ('LAYUP', 'Layup')], max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='layup_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
