# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='upvotes',
            field=models.IntegerField(null=True),
        ),
    ]
