# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20160102_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='confirmed_email',
        ),
    ]
