# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_vote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='crosslisted_courses',
            field=models.ManyToManyField(blank=True, related_name='_course_crosslisted_courses_+', to='web.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='distribs',
            field=models.ManyToManyField(blank=True, to='web.DistributiveRequirement'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subnumber',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
