department_code_to_name = {
    "AAAS": "African and African American Studies",
    "AMEL": "Asian and Middle Eastern Languages and Literatures",
    "AMES": "Asian and Middle Eastern Studies",
    "ANTH": "Anthropology",
    "ARAB": "Arabic",
    "ARTH": "Art History",
    "ASTR": "Astronomy",
    "BIOL": "Biological Sciences",
    "CHEM": "Chemistry",
    "CHIN": "Chinese",
    "CLST": "Classical Studies",
    "COCO": "College Courses",
    "COGS": "Cognitive Science",
    "COLT": "Comparative Literature",
    "COSC": "Computer Science",
    "EARS": "Earth Sciences",
    "ECON": "Economics",
    "EDUC": "Education",
    "ENGL": "English",
    "ENGS": "Engineering Sciences",
    "ENVS": "Environmental Studies",
    "FILM": "Film and Media Studies",
    "FREN": "French",
    "FRIT": "French and Italian in Translation",
    "GEOG": "Geography",
    "GERM": "German Studies",
    "GOVT": "Government",
    "GRK": "Greek",
    "HEBR": "Hebrew",
    "HIST": "History",
    "HUM": "Humanities",
    "INTS": "International Studies",
    "ITAL": "Italian",
    "JAPN": "Japanese",
    "JWST": "Jewish Studies",
    "LACS": "Latin American and Caribbean Studies",
    "LAT": "Latin",
    "LATS": "Latino Studies",
    "LING": "Linguistics",
    "MATH": "Mathematics",
    "MUS": "Music",
    "NAS": "Native American Studies",
    "PBPL": "Public Policy",
    "PHIL": "Philosophy",
    "PHYS": "Physics",
    "PORT": "Portuguese",
    "PSYC": "Psychological and Brain Sciences",
    "QSS": "Quantitative Social Science",
    "REL": "Religion",
    "RUSS": "Russian Language and Literature",
    "SART": "Studio Art",
    "SOCY": "Sociology",
    "SPAN": "Spanish",
    "SPEE": "Speech",
    "SSOC": "Social Science",
    "SUPP": "2016 Supplement",
    "THEA": "Theater",
    "TUCK": "Tuck Undergraduate Courses",
    "WGSS": "Women's, Gender, and Sexuality Studies",
    "WRIT": "Writing Courses",
}


def get_department_name(department_code):
    return department_code_to_name.get(department_code)
